from pydantic import BaseModel, Field
from typing import Optional

class HousePredictionInput(BaseModel):
    MSSubClass: Optional[int] = Field(default=None, description='MSSubClass feature')
    MSZoning: Optional[str] = Field(default=None, description='MSZoning feature')
    LotFrontage: Optional[float] = Field(default=None, description='LotFrontage feature')
    LotArea: Optional[int] = Field(default=None, description='LotArea feature')
    Street: Optional[str] = Field(default=None, description='Street feature')
    Alley: Optional[str] = Field(default=None, description='Alley feature')
    LotShape: Optional[str] = Field(default=None, description='LotShape feature')
    LandContour: Optional[str] = Field(default=None, description='LandContour feature')
    Utilities: Optional[str] = Field(default=None, description='Utilities feature')
    LotConfig: Optional[str] = Field(default=None, description='LotConfig feature')
    LandSlope: Optional[str] = Field(default=None, description='LandSlope feature')
    Neighborhood: Optional[str] = Field(default=None, description='Neighborhood feature')
    Condition1: Optional[str] = Field(default=None, description='Condition1 feature')
    Condition2: Optional[str] = Field(default=None, description='Condition2 feature')
    BldgType: Optional[str] = Field(default=None, description='BldgType feature')
    HouseStyle: Optional[str] = Field(default=None, description='HouseStyle feature')
    OverallQual: Optional[int] = Field(default=None, description='OverallQual feature')
    OverallCond: Optional[int] = Field(default=None, description='OverallCond feature')
    YearBuilt: Optional[int] = Field(default=None, description='YearBuilt feature')
    YearRemodAdd: Optional[int] = Field(default=None, description='YearRemodAdd feature')
    RoofStyle: Optional[str] = Field(default=None, description='RoofStyle feature')
    RoofMatl: Optional[str] = Field(default=None, description='RoofMatl feature')
    Exterior1st: Optional[str] = Field(default=None, description='Exterior1st feature')
    Exterior2nd: Optional[str] = Field(default=None, description='Exterior2nd feature')
    MasVnrType: Optional[str] = Field(default=None, description='MasVnrType feature')
    MasVnrArea: Optional[float] = Field(default=None, description='MasVnrArea feature')
    ExterQual: Optional[str] = Field(default=None, description='ExterQual feature')
    ExterCond: Optional[str] = Field(default=None, description='ExterCond feature')
    Foundation: Optional[str] = Field(default=None, description='Foundation feature')
    BsmtQual: Optional[str] = Field(default=None, description='BsmtQual feature')
    BsmtCond: Optional[str] = Field(default=None, description='BsmtCond feature')
    BsmtExposure: Optional[str] = Field(default=None, description='BsmtExposure feature')
    BsmtFinType1: Optional[str] = Field(default=None, description='BsmtFinType1 feature')
    BsmtFinSF1: Optional[int] = Field(default=None, description='BsmtFinSF1 feature')
    BsmtFinType2: Optional[str] = Field(default=None, description='BsmtFinType2 feature')
    BsmtFinSF2: Optional[int] = Field(default=None, description='BsmtFinSF2 feature')
    BsmtUnfSF: Optional[int] = Field(default=None, description='BsmtUnfSF feature')
    TotalBsmtSF: Optional[int] = Field(default=None, description='TotalBsmtSF feature')
    Heating: Optional[str] = Field(default=None, description='Heating feature')
    HeatingQC: Optional[str] = Field(default=None, description='HeatingQC feature')
    CentralAir: Optional[str] = Field(default=None, description='CentralAir feature')
    Electrical: Optional[str] = Field(default=None, description='Electrical feature')
    FirstFlrSF: Optional[int] = Field(default=None, alias='1stFlrSF', description='1stFlrSF feature')
    SecondFlrSF: Optional[int] = Field(default=None, alias='2ndFlrSF', description='2ndFlrSF feature')
    LowQualFinSF: Optional[int] = Field(default=None, description='LowQualFinSF feature')
    GrLivArea: Optional[int] = Field(default=None, description='GrLivArea feature')
    BsmtFullBath: Optional[int] = Field(default=None, description='BsmtFullBath feature')
    BsmtHalfBath: Optional[int] = Field(default=None, description='BsmtHalfBath feature')
    FullBath: Optional[int] = Field(default=None, description='FullBath feature')
    HalfBath: Optional[int] = Field(default=None, description='HalfBath feature')
    BedroomAbvGr: Optional[int] = Field(default=None, description='BedroomAbvGr feature')
    KitchenAbvGr: Optional[int] = Field(default=None, description='KitchenAbvGr feature')
    KitchenQual: Optional[str] = Field(default=None, description='KitchenQual feature')
    TotRmsAbvGrd: Optional[int] = Field(default=None, description='TotRmsAbvGrd feature')
    Functional: Optional[str] = Field(default=None, description='Functional feature')
    Fireplaces: Optional[int] = Field(default=None, description='Fireplaces feature')
    FireplaceQu: Optional[str] = Field(default=None, description='FireplaceQu feature')
    GarageType: Optional[str] = Field(default=None, description='GarageType feature')
    GarageYrBlt: Optional[float] = Field(default=None, description='GarageYrBlt feature')
    GarageFinish: Optional[str] = Field(default=None, description='GarageFinish feature')
    GarageCars: Optional[int] = Field(default=None, description='GarageCars feature')
    GarageArea: Optional[int] = Field(default=None, description='GarageArea feature')
    GarageQual: Optional[str] = Field(default=None, description='GarageQual feature')
    GarageCond: Optional[str] = Field(default=None, description='GarageCond feature')
    PavedDrive: Optional[str] = Field(default=None, description='PavedDrive feature')
    WoodDeckSF: Optional[int] = Field(default=None, description='WoodDeckSF feature')
    OpenPorchSF: Optional[int] = Field(default=None, description='OpenPorchSF feature')
    EnclosedPorch: Optional[int] = Field(default=None, description='EnclosedPorch feature')
    ThreeSsnPorch: Optional[int] = Field(default=None, alias='3SsnPorch', description='3SsnPorch feature')
    ScreenPorch: Optional[int] = Field(default=None, description='ScreenPorch feature')
    PoolArea: Optional[int] = Field(default=None, description='PoolArea feature')
    PoolQC: Optional[str] = Field(default=None, description='PoolQC feature')
    Fence: Optional[str] = Field(default=None, description='Fence feature')
    MiscFeature: Optional[str] = Field(default=None, description='MiscFeature feature')
    MiscVal: Optional[int] = Field(default=None, description='MiscVal feature')
    MoSold: Optional[int] = Field(default=None, description='MoSold feature')
    YrSold: Optional[int] = Field(default=None, description='YrSold feature')
    SaleType: Optional[str] = Field(default=None, description='SaleType feature')
    SaleCondition: Optional[str] = Field(default=None, description='SaleCondition feature')

    model_config = {
        'populate_by_name': True,
        'populate_by_alias': True,
    }

class HousePredictionOutput(BaseModel):
    predicted_price: float = Field(..., description='Predicted Sale Price of the house in USD')